name: dart_get_upto_speed
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  path: ^1.8.0
  riverpod: ^0.14.0+3

dev_dependencies:
  lints: ^1.0.0
