name: dart_get_upto_speed
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  freezed_annotation: ^0.15.0
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^0.15.0+1
  lint: ^1.7.2
